controller_list:
  - name: "arm_controller"
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
  - name: "gripper"
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - gripper_finger1_joint
      - gripper_finger2_joint


  # - name: "gripper"
  #   type: GripperCommand
  #   action_ns: gripper_action
  #   default: true
  #   parallel: true
  #   joints:
  #     - gripper_finger1_joint
  #     - gripper_finger2_joint
     