ur5:
# MoveIt-specific simulation settings
  moveit_sim_hw_interface:
    joint_model_group: controllers_initial_group_
    joint_model_group_pose: controllers_initial_pose_
# Settings for ros_control control loop
  generic_hw_control_loop:
    loop_hz: 300
    cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
  hardware_interface:
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
      - gripper_finger1_joint
      - 2_shoulder_pan_joint
      - 2_shoulder_lift_joint
      - 2_elbow_joint
      - 2_wrist_1_joint
      - 2_wrist_2_joint
      - 2_wrist_3_joint
      - 2_gripper_finger1_joint
    sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
  controller_list:
    []
  right_ur5_arm_controller:
    type: position_controllers/JointPositionController
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
    gains:
      shoulder_pan_joint:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      shoulder_lift_joint:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      elbow_joint:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      wrist_1_joint:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      wrist_2_joint:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      wrist_3_joint:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
  left_ur5_arm:
    type: position_controllers/JointPositionController
    joints:
      - 2_shoulder_pan_joint
      - 2_shoulder_lift_joint
      - 2_elbow_joint
      - 2_wrist_1_joint
      - 2_wrist_2_joint
      - 2_wrist_3_joint
    gains:
      2_shoulder_pan_joint:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      2_shoulder_lift_joint:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      2_elbow_joint:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      2_wrist_1_joint:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      2_wrist_2_joint:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      2_wrist_3_joint:
        p: 100
        d: 1
        i: 1
        i_clamp: 1